/**
 * App-level types.
 * These are derived from the database schema but shaped for use in the UI.
 * Raw database types live in database.types.ts (auto-generated by Supabase CLI).
 */

// ─── Plan ─────────────────────────────────────────────────────────────────────

export type PlanName = "starter" | "growth" | "pro"

export interface Plan {
  id: string
  name: PlanName
  price_mad: number
  max_stores: number
  max_products: number | null // null = unlimited
  has_custom_domain: boolean
  has_analytics: boolean
  has_whatsapp: boolean
  has_staff: boolean
  has_api: boolean
}

// ─── Store ────────────────────────────────────────────────────────────────────

export type StoreTheme = "minimal" | "bold" | "elegant"

export interface Store {
  id: string
  user_id: string
  name: string
  slug: string
  description: string | null
  logo_url: string | null
  banner_url: string | null
  theme: StoreTheme
  theme_config: Record<string, unknown>
  custom_domain: string | null
  whatsapp_number: string | null
  is_active: boolean
  meta_title: string | null
  meta_description: string | null
  created_at: string
  updated_at: string
}

// ─── Category ─────────────────────────────────────────────────────────────────

export interface Category {
  id: string
  store_id: string
  name: string
  slug: string
  sort_order: number
  created_at: string
  updated_at: string
}

/** Category row with product count (used in dashboard lists). */
export interface CategoryWithCount extends Category {
  product_count: number
}

// ─── Product & Variants ───────────────────────────────────────────────────────

export interface Product {
  id: string
  store_id: string
  name: string
  description: string | null
  category: string | null
  category_id: string | null
  base_price: number
  compare_price: number | null
  images: string[]
  is_active: boolean
  is_featured: boolean
  slug: string
  meta_title: string | null
  meta_description: string | null
  created_at: string
  updated_at: string
}

export type AttributeDisplayType = "select" | "color_swatch" | "text" | "button"

export interface AttributeDefinition {
  id: string
  store_id: string
  name: string
  display_type: AttributeDisplayType
  is_required: boolean
  sort_order: number
  values?: AttributeValue[]
}

export interface AttributeValue {
  id: string
  attribute_definition_id: string
  label: string
  value: string
  color_hex: string | null
  sort_order: number
}

export interface ProductVariant {
  id: string
  product_id: string
  sku: string | null
  price_override: number | null
  stock_quantity: number
  images: string[]
  is_active: boolean
  // Resolved attributes (joined from variant_attribute_values)
  attributes?: VariantAttributeSummary[]
}

export interface VariantAttributeSummary {
  definition_name: string // "Taille"
  value_label: string     // "M"
  color_hex: string | null
}

// Full product with variants (used in storefront and dashboard)
export interface ProductWithVariants extends Product {
  variants: ProductVariant[]
  attribute_definitions: AttributeDefinition[]
}

/** Dashboard inventaire — one row per product with aggregated variant / stock fields. */
export interface ProductDashboardListRow {
  id: string
  name: string
  slug: string
  category: string | null
  category_id: string | null
  base_price: number
  is_active: boolean
  images: string[]
  /** Merchant-facing ref line (SKU or short id), e.g. "REF: SKU-001". */
  reference_label: string
  variant_count: number
  total_stock: number
  created_at: string
}

// ─── Order ────────────────────────────────────────────────────────────────────

export type OrderStatus =
  | "pending"
  | "confirmed"
  | "shipped"
  | "delivered"
  | "returned"
  | "cancelled"

/** Lightweight row for dashboard/API list — no order_items lines, aggregated count only. */
export interface OrderListItem {
  id: string
  store_id: string
  order_number: string
  status: OrderStatus
  customer_name: string
  customer_phone: string
  total_mad: number
  wilaya_name: string | null
  items_count: number
  created_at: string
}

export interface Order {
  id: string
  store_id: string
  order_number: string
  status: OrderStatus
  customer_name: string
  customer_phone: string
  customer_address: string
  customer_city: string
  wilaya_id: number
  customer_notes: string | null
  subtotal_mad: number
  shipping_cost_mad: number
  total_mad: number
  shipping_provider_id: string | null
  tracking_number: string | null
  confirmed_at: string | null
  shipped_at: string | null
  delivered_at: string | null
  returned_at: string | null
  cancelled_at: string | null
  created_at: string
  updated_at: string
  // Joined
  items?: OrderItem[]
  wilaya?: Wilaya
}

export interface OrderItem {
  id: string
  order_id: string
  product_id: string | null
  variant_id: string | null
  // Snapshots — always use these, never join to live product
  product_name: string
  variant_label: string
  product_image: string | null
  quantity: number
  unit_price_mad: number
  total_price_mad: number
}

// ─── Shipping ─────────────────────────────────────────────────────────────────

export interface Wilaya {
  id: number
  name_fr: string
  name_ar: string
  code: string
}

export interface ShippingZone {
  id: string
  store_id: string
  wilaya_id: number
  provider_id: string | null
  price_mad: number
  free_shipping_threshold: number | null
  estimated_days_min: number
  estimated_days_max: number
  is_active: boolean
  wilaya?: Wilaya
}

/** Zone de livraison avec wilaya jointe (liste paramètres / API). */
export type ShippingZoneWithWilaya = ShippingZone & { wilaya: Wilaya }

/** Données initiales pour `/dashboard/settings` (RSC → client). */
export interface StoreSettingsInitialData {
  store: Pick<Store, "id" | "name" | "slug" | "logo_url" | "banner_url" | "whatsapp_number">
  shipping_zones: ShippingZoneWithWilaya[]
  wilayas: Wilaya[]
  /** `NEXT_PUBLIC_ROOT_DOMAIN` — suffixe public du sous-domaine boutique. */
  rootDomain: string
}

export interface ShippingProvider {
  id: string
  name: string
  logo_url: string | null
  is_active: boolean
}

// ─── Analytics ────────────────────────────────────────────────────────────────

export type AnalyticsEventType =
  | "page_view"
  | "product_view"
  | "cart_add"
  | "cart_remove"
  | "checkout_start"
  | "checkout_abandon"
  | "order_placed"
  | "order_delivered"
  | "order_returned"

export interface AnalyticsEvent {
  store_id: string
  event_type: AnalyticsEventType
  product_id?: string
  order_id?: string
  session_id?: string
  wilaya_id?: number
  referrer?: string
  utm_source?: string
  utm_medium?: string
  utm_campaign?: string
  device_type?: "mobile" | "tablet" | "desktop"
}

// Dashboard analytics aggregates
export interface RevenueDataPoint {
  date: string
  revenue: number
  orders: number
}

/** Shared analytics window presets in Casablanca timezone. */
export type AnalyticsDatePreset = "today" | "yesterday" | "7d" | "30d" | "custom"
/** Compare presets reuse the same options. */
export type AnalyticsComparePreset = AnalyticsDatePreset

export interface AnalyticsDateWindow {
  preset: AnalyticsDatePreset
  start_date_key: string
  end_date_key_inclusive: string
  from_inclusive_iso: string
  to_exclusive_iso: string
  day_count: number
  label_fr: string
}

/** One chart row: aligned by day index (1…N) for current vs previous period. */
export interface AnalyticsRevenueCompareChartRow {
  dayIndex: number
  /** Short label (e.g. day / date) for the X axis. */
  labelShort: string
  current_revenue: number
  previous_revenue: number
  current_orders: number
  previous_orders: number
}

/** Daily counts per analytics event type (server-aggregated only). */
export interface AnalyticsEventsDailyRow {
  date: string
  page_view: number
  product_view: number
  cart_add: number
  cart_remove: number
  checkout_start: number
  checkout_abandon: number
  order_placed: number
  order_delivered: number
  order_returned: number
}

export interface AnalyticsRevenueCompareSnapshot {
  preset: AnalyticsComparePreset
  window: AnalyticsDateWindow
  current_range: {
    from_inclusive_iso: string
    to_exclusive_iso: string
    start_date_key: string
    end_date_key_inclusive: string
    label_fr: string
  }
  previous_range: {
    from_inclusive_iso: string
    to_exclusive_iso: string
    start_date_key: string
    end_date_key_inclusive: string
    label_fr: string
  }
  chart_rows: AnalyticsRevenueCompareChartRow[]
  summary: {
    current: { revenue_mad: number; orders: number; avg_order_mad: number }
    previous: { revenue_mad: number; orders: number; avg_order_mad: number }
    delta_revenue_pct: number | null
    delta_orders_pct: number | null
    delta_avg_order_pct: number | null
  }
}

export interface AnalyticsOverviewDailyRow {
  date: string
  totalOrders: number
  completedOrders: number
  cancelledOrders: number
  inProgressOrders: number
  completionRate: number
  cancellationRate: number
}

export interface AnalyticsOverviewSnapshot {
  window: AnalyticsDateWindow
  dailyStats: AnalyticsOverviewDailyRow[]
  summary: {
    totalOrders: number
    completedOrders: number
    cancelledOrders: number
    inProgressOrders: number
    completionRate: number
    cancellationRate: number
  }
}

export interface AnalyticsRevenueSnapshot {
  window: AnalyticsDateWindow
  dailySales: RevenueDataPoint[]
  monthlyGrowth: number | null
}

export interface AnalyticsBreakdownBucket {
  key: string
  revenue: number
  collectedRevenue: number
  outstanding: number
  collectionRate: number
  orderCount: number
  avgOrderValue: number
  percentage: number
  paidOrders: number
  partialOrders: number
  unpaidOrders: number
}

export interface AnalyticsBreakdownSnapshot {
  window: AnalyticsDateWindow
  byChannel: AnalyticsBreakdownBucket[]
  byOrderType: AnalyticsBreakdownBucket[]
}

export interface AnalyticsFulfillmentSnapshot {
  window: AnalyticsDateWindow
  averagePreparationTime: string
  averageDeliveryTime: string
  onTimeDeliveryRate: number
  lateOrders: number
  cancellationRate: number
  totalOrders: number
}

export interface AnalyticsCancellationSnapshot {
  window: AnalyticsDateWindow
  totalCancellations: number
  cancellationRate: number
  estimatedRevenueLost: number
  dailyCancellations: Array<{
    date: string
    cancellations: number
    totalOrders: number
    rate: number
  }>
}

export interface AnalyticsPeakHoursSnapshot {
  window: AnalyticsDateWindow
  peakHours: Array<{ hour: number; orders: number; revenue: number }>
  busiestDay: string
  dailyPattern: Record<string, { orders: number; revenue: number }>
}

export interface FunnelData {
  product_views: number
  cart_adds: number
  checkout_starts: number
  orders_placed: number
  cart_conversion_rate: number
  checkout_conversion_rate: number
}

export interface TopProduct {
  product_id: string
  product_name: string
  product_image: string | null
  units_sold: number
  revenue: number
}

// ─── Cart (client-side only, not persisted to DB) ────────────────────────────

export interface CartItem {
  variant_id: string
  product_id: string
  product_name: string
  variant_label: string
  product_image: string | null
  quantity: number
  unit_price_mad: number
}

export interface Cart {
  store_id: string
  items: CartItem[]
  subtotal_mad: number
}

// ─── Merchant profile & subscription (dashboard) ───────────────────────────

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "past_due"

/** `profiles` row — marchand. */
export interface MerchantProfile {
  id: string
  full_name: string
  phone: string | null
  avatar_url: string | null
  created_at: string
  updated_at: string
}

/** `subscriptions` + plan joint (liste dashboard). */
export interface SubscriptionWithPlan {
  id: string
  user_id: string
  plan_id: string
  status: SubscriptionStatus
  current_period_start: string
  current_period_end: string
  plan: Plan
}

/** Données pour `/dashboard/profile` (RSC → client). */
export interface ProfilePageData {
  email: string
  profile: MerchantProfile
  subscription: SubscriptionWithPlan
  plans: Plan[]
}

// ─── Tenant context (resolved by middleware) ─────────────────────────────────

export interface TenantContext {
  store: Store
  plan: Plan
}

// ─── API response helpers ─────────────────────────────────────────────────────

export type ApiSuccess<T> = { data: T; error: null }
export type ApiError = { data: null; error: string }
export type ApiResponse<T> = ApiSuccess<T> | ApiError