/**
 * App-level types.
 * These are derived from the database schema but shaped for use in the UI.
 * Raw database types live in database.types.ts (auto-generated by Supabase CLI).
 */

// ─── Plan ─────────────────────────────────────────────────────────────────────

export type PlanName = "starter" | "growth" | "pro"

export interface Plan {
  id: string
  name: PlanName
  price_mad: number
  max_stores: number
  max_products: number | null // null = unlimited
  has_custom_domain: boolean
  has_analytics: boolean
  has_whatsapp: boolean
  has_staff: boolean
  has_api: boolean
}

// ─── Store ────────────────────────────────────────────────────────────────────

export type StoreTheme = "minimal" | "bold" | "elegant"

export interface Store {
  id: string
  user_id: string
  name: string
  slug: string
  description: string | null
  logo_url: string | null
  banner_url: string | null
  theme: StoreTheme
  theme_config: Record<string, unknown>
  custom_domain: string | null
  whatsapp_number: string | null
  is_active: boolean
  meta_title: string | null
  meta_description: string | null
  created_at: string
  updated_at: string
}

// ─── Product & Variants ───────────────────────────────────────────────────────

export interface Product {
  id: string
  store_id: string
  name: string
  description: string | null
  category: string | null
  base_price: number
  compare_price: number | null
  images: string[]
  is_active: boolean
  is_featured: boolean
  slug: string
  meta_title: string | null
  meta_description: string | null
  created_at: string
  updated_at: string
}

export type AttributeDisplayType = "select" | "color_swatch" | "text" | "button"

export interface AttributeDefinition {
  id: string
  store_id: string
  name: string
  display_type: AttributeDisplayType
  is_required: boolean
  sort_order: number
  values?: AttributeValue[]
}

export interface AttributeValue {
  id: string
  attribute_definition_id: string
  label: string
  value: string
  color_hex: string | null
  sort_order: number
}

export interface ProductVariant {
  id: string
  product_id: string
  sku: string | null
  price_override: number | null
  stock_quantity: number
  images: string[]
  is_active: boolean
  // Resolved attributes (joined from variant_attribute_values)
  attributes?: VariantAttributeSummary[]
}

export interface VariantAttributeSummary {
  definition_name: string // "Taille"
  value_label: string     // "M"
  color_hex: string | null
}

// Full product with variants (used in storefront and dashboard)
export interface ProductWithVariants extends Product {
  variants: ProductVariant[]
  attribute_definitions: AttributeDefinition[]
}

// ─── Order ────────────────────────────────────────────────────────────────────

export type OrderStatus =
  | "pending"
  | "confirmed"
  | "shipped"
  | "delivered"
  | "returned"
  | "cancelled"

export interface Order {
  id: string
  store_id: string
  order_number: string
  status: OrderStatus
  customer_name: string
  customer_phone: string
  customer_address: string
  customer_city: string
  wilaya_id: number
  customer_notes: string | null
  subtotal_mad: number
  shipping_cost_mad: number
  total_mad: number
  shipping_provider_id: string | null
  tracking_number: string | null
  confirmed_at: string | null
  shipped_at: string | null
  delivered_at: string | null
  returned_at: string | null
  cancelled_at: string | null
  created_at: string
  updated_at: string
  // Joined
  items?: OrderItem[]
  wilaya?: Wilaya
}

export interface OrderItem {
  id: string
  order_id: string
  product_id: string | null
  variant_id: string | null
  // Snapshots — always use these, never join to live product
  product_name: string
  variant_label: string
  product_image: string | null
  quantity: number
  unit_price_mad: number
  total_price_mad: number
}

// ─── Shipping ─────────────────────────────────────────────────────────────────

export interface Wilaya {
  id: number
  name_fr: string
  name_ar: string
  code: string
}

export interface ShippingZone {
  id: string
  store_id: string
  wilaya_id: number
  provider_id: string | null
  price_mad: number
  free_shipping_threshold: number | null
  estimated_days_min: number
  estimated_days_max: number
  is_active: boolean
  wilaya?: Wilaya
}

export interface ShippingProvider {
  id: string
  name: string
  logo_url: string | null
  is_active: boolean
}

// ─── Analytics ────────────────────────────────────────────────────────────────

export type AnalyticsEventType =
  | "page_view"
  | "product_view"
  | "cart_add"
  | "cart_remove"
  | "checkout_start"
  | "checkout_abandon"
  | "order_placed"
  | "order_delivered"
  | "order_returned"

export interface AnalyticsEvent {
  store_id: string
  event_type: AnalyticsEventType
  product_id?: string
  order_id?: string
  session_id?: string
  wilaya_id?: number
  referrer?: string
  utm_source?: string
  utm_medium?: string
  utm_campaign?: string
  device_type?: "mobile" | "tablet" | "desktop"
}

// Dashboard analytics aggregates
export interface RevenueDataPoint {
  date: string
  revenue: number
  orders: number
}

export interface FunnelData {
  product_views: number
  cart_adds: number
  checkout_starts: number
  orders_placed: number
  cart_conversion_rate: number
  checkout_conversion_rate: number
}

export interface TopProduct {
  product_id: string
  product_name: string
  product_image: string | null
  units_sold: number
  revenue: number
}

// ─── Cart (client-side only, not persisted to DB) ────────────────────────────

export interface CartItem {
  variant_id: string
  product_id: string
  product_name: string
  variant_label: string
  product_image: string | null
  quantity: number
  unit_price_mad: number
}

export interface Cart {
  store_id: string
  items: CartItem[]
  subtotal_mad: number
}

// ─── Tenant context (resolved by middleware) ─────────────────────────────────

export interface TenantContext {
  store: Store
  plan: Plan
}

// ─── API response helpers ─────────────────────────────────────────────────────

export type ApiSuccess<T> = { data: T; error: null }
export type ApiError = { data: null; error: string }
export type ApiResponse<T> = ApiSuccess<T> | ApiError